# Generated by Django 6.0.1 on 2026-01-28 19:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_views', models.PositiveIntegerField(blank=True, null=True)),
                ('remaining_views', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pastes',
                'ordering': ['-created_at'],
            },
        ),
    ]
